import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";

import { Syne } from "next/font/google";
import AnimatedBackground from "./components/animated-background";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

const syne = Syne({
  weight: ["400", "700", "800"],
  variable: "--font-syne",
  subsets: ["latin"],
});

import { Nunito } from "next/font/google";
const nunito = Nunito({
  subsets: ["latin"],
  weight: ["400", "700", "900"],
  variable: "--font-nunito",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`relative bg-[#e990fb27] ${geistSans.variable} ${geistMono.variable} ${syne.className} ${nunito.className} antialiased`}
      >
        <AnimatedBackground />
        {children}
      </body>
    </html>
  );
}
